name: Merge Main

on:
  push:
    branches:
      - main

concurency: deploy

jobs:
  build-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image-digest: ${{ steps.docker_build_outputs.digest }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-actions@v2

      -
        name: Docker Meta
